### ISSUE TITLE
[Folia] Error occurred while enabling CMILib

### ISSUE THREAD

**Issue by xyfwdy** [Zrips/CMILib#29]
This server is running Folia version git-Folia-"b2d7bdb" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b2d7bdb)
You are running the latest version

CMILib version 1.4.0.3

```
Error occurred while enabling CMILib v1.4.0.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Class.cast(Object)" because "this.CraftWorldClass" is null
        at net.Zrips.CMILib.Reflections.getCraftWorld(Reflections.java:770) ~[CMILib1.4.0.3.jar:?]
        at net.Zrips.CMILib.Reflections.getServerName(Reflections.java:759) ~[CMILib1.4.0.3.jar:?]
        at net.Zrips.CMILib.commands.CommandsHandler.<init>(CommandsHandler.java:59) ~[CMILib1.4.0.3.jar:?]
        at net.Zrips.CMILib.CMILib.getCommandManager(CMILib.java:112) ~[CMILib1.4.0.3.jar:?]
        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:303) ~[CMILib1.4.0.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-"b2d7bdb"]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by Zrips** [comment]
Will post new CMILib version which should atleast allow you to fully load in plugin. But your error should not really happen if you have your worlds properly loaded in or your server have atleast one valid world. New version will be posted shortly.
