### ISSUE TITLE
when use /spawn and delay it cant back to the spawnpoint in kaiijiu1.20.1

### ISSUE THREAD

**Issue by BallkingCN** [Zrips/CMILib#43]
[14:06:18 ERROR]: Thread Region Scheduler Thread #2 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:83) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:719) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.performCmd(WarmUpManager.java:322) ~[1712648403419CMI-9.7.0.4.jar:?]
        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.lambda$0(WarmUpManager.java:354) ~[1712648403419CMI-9.7.0.4.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$scheduleSyncRepeatingTask$4(CMIFoliaImpl.java:69) ~[CMILib1.4.6.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:06:18 WARN]: [CMILib] Global task for CMILib v1.4.6.2 generated an exception
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:84) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:719) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.performCmd(WarmUpManager.java:322) ~[1712648403419CMI-9.7.0.4.jar:?]
        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.lambda$0(WarmUpManager.java:354) ~[1712648403419CMI-9.7.0.4.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$scheduleSyncRepeatingTask$4(CMIFoliaImpl.java:69) ~[CMILib1.4.6.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

when the 3 2 1 finish it wont teleport player back to spawnpoint.and CMIlib will show this error

**Comment by BallkingCN** [comment]
**when the 3 2 1 finish it wont teleport player back to spawnpoint.and CMIlib will show this error**
