### ISSUE TITLE
CMILib1.4.7.3 problems

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMILib#44]
Problem just with newest CMI + CMILib (1.20.4 purpur):

[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.lambda$2(SelectionManager.java:800)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:11:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:11:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[22:11:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData.getState()" because "data" is null
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle.createParticleParam(CraftParticle.java:68)
[22:11:02 WARN]:        ... 13 more
[22:11:02 WARN]: java.lang.reflect.InvocationTargetException
[22:11:02 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
[22:11:02 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:11:02 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Reflections.playEffect(Reflections.java:1848)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.showParticles(SelectionManager.java:861)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.lambda$2(SelectionManager.java:800)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:11:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:11:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[22:11:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData.getState()" because "data" is null
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle.createParticleParam(CraftParticle.java:68)
[22:11:02 WARN]:        ... 13 more
[22:11:02 WARN]: java.lang.reflect.InvocationTargetException
[22:11:02 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
[22:11:02 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:11:02 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Reflections.playEffect(Reflections.java:1848)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.showParticles(SelectionManager.java:861)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.lambda$2(SelectionManager.java:800)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:11:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:11:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[22:11:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData.getState()" because "data" is null
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle.createParticleParam(CraftParticle.java:68)
[22:11:02 WARN]:        ... 13 more
[22:11:02 WARN]: java.lang.reflect.InvocationTargetException
[22:11:02 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
[22:11:02 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:11:02 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Reflections.playEffect(Reflections.java:1848)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.showParticles(SelectionManager.java:861)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.lambda$2(SelectionManager.java:800)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:11:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:11:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[22:11:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData.getState()" because "data" is null
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle.createParticleParam(CraftParticle.java:68)
[22:11:02 WARN]:        ... 13 more
[22:11:02 WARN]: java.lang.reflect.InvocationTargetException
[22:11:02 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
[22:11:02 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:11:02 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Reflections.playEffect(Reflections.java:1848)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.showParticles(SelectionManager.java:861)
[22:11:02 WARN]:        at Residence5.1.4.3.jar//com.bekvon.bukkit.residence.selection.SelectionManager.lambda$2(SelectionManager.java:800)
[22:11:02 WARN]:        at CMILib1.4.7.3.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:11:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:11:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:11:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[22:11:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData.getState()" because "data" is null
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[22:11:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftParticle.createParticleParam(CraftParticle.java:68)
[22:11:02 WARN]:        ... 13 more

**Comment by Zrips** [comment]
Should be resolved now
