### ISSUE TITLE
CMIlib Version 1.4.7.11 not compatible with 1.16.5

### ISSUE THREAD

**Issue by byrra** [Zrips/CMILib#46]
Just wanted to let you know that the above version is not compatible with 1.16.5
Version 1.4.7.8 works fine.

[16:18:22 ERROR]: Error occurred while enabling CMILib v1.4.7.11 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Vibration$Destination
        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:90) ~[?:?]
        at net.Zrips.CMILib.Version.Version.<clinit>(Version.java:72) ~[?:?]
        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:77) ~[?:?]
        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:215) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Vibration$Destination
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 14 more
[16:18:22 INFO]: [CMILib] Disabling CMILib v1.4.7.11

**Comment by Achent007** [comment]
Same for 1.12.2
